language: node_js

node_js:
  - 4.1
  - 4
  - 5

services:
  - mongodb

before_install:
  - sudo apt-get install build-essential
  - sudo apt-get install gcc
  - sudo apt-get install g++

script: npm test
after_success: npm run test-lcov

sudo: true
