env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

language: node_js

node_js:
  - 4.1

services:
  - mongodb

script: npm test
after_success: npm run test-lcov

sudo: true
