language: node_js

node_js:
  - 0.12

services:
  - mongodb

script: echo "\n //////// UNIT TESTS" && npm run test-unit && echo '//////// INTEGRATION TESTS' && npm run test-integration && npm run test-lcov
