language: node_js

node_js:
  - 0.12

services:
  - mongodb

script: echo '//////// UNIT TESTS \n' && npm test-unit && echo '//////// INTEGRATION TESTS \n' && npm run test-integration && npm run test-lcov
